
version: 2.1

workflows:
  build:
    jobs:
      - build
jobs:
    build:
        working_directory: ~/circleci-starter
        docker:
            - image: cimg/base:2022.09
            - image: cimg/node:14.15.0 # Primary execution image
        steps:
            - checkout
            - setup_remote_docker:
                version: 20.10.14
            - run:
                name: build
                command: |
                    # Build
                      echo '_____________beginning build'
                      docker build -t udagram-api-feed:v4 ./udagram-api-feed
                      docker build -t udagram-api-user:v4 ./udagram-api-user
                      docker build -t udagram-frontend:v4 ./udagram-frontend
                      docker build -t reverseproxy:v4 ./udagram-reverseproxy  

                      # Tagging
                      echo '_____________beginning tag'
                      docker tag udagram-api-feed:v4 devopnguyenan88/udagram-api-feed:v4
                      docker tag udagram-api-user:v4 devopnguyenan88/udagram-api-user:v4
                      docker tag udagram-frontend:v4 devopnguyenan88/udagram-frontend:v4
                      docker tag reverseproxy:v4 devopnguyenan88/reverseproxy:v4

                      echo 'DOCKER IMAGE LS____'
                      docker image ls

            - run:
                name: after_success
                command: |
                    # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
                    # Login Docker  
                    echo '________LOGIN_______'
                    #- docker login -u=devopnguyenan88 -p=xxxxxx
                    docker login -u devopnguyenan88 -p $DOCKERPASS
                    # Pushing 
                    echo '_____________beginning push image'
                    docker push devopnguyenan88/udagram-api-feed:v4
                    docker push devopnguyenan88/udagram-api-user:v4
                    docker push devopnguyenan88/udagram-frontend:v4
                    docker push devopnguyenan88/reverseproxy:v4
          
